### ISSUE TITLE
How do I reset/change remembered configurations?

### ISSUE THREAD

**Issue by robblovell** [joeferner/redis-commander#114]
I have a bunch of configured servers in redis-commander and recently, most of them were decommissioned.  How do I remove them so that redis commander doesn't error out trying to connect?

Redis error Error: Redis connection to squawfish.redistogo.com:9754 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Redis error Error: Redis connection to barreleye.redistogo.com:9985 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)

**Comment by mitchellporter** [comment]
Deleting the `.redis-commander` file did the trick for me!

**Comment by sseide** [comment]
The feature requested is available with latest version. There is a cli param to start redis commander with "--clear-config" which removes all server connections configured. Additionally disconnection from servers via the UI is available too.

If there is something missing at the implementation feel free to reopen issue with an updated description.
