### ISSUE TITLE
Not compatible with node v0.11.7

### ISSUE THREAD

**Issue by ysmood** [joeferner/redis-commander#115]
When using node v0.11.7, issues this error infomation:

```
 path.existsSync is now called `fs.existsSync`.
/home/saya/.nvm/v0.11.7/lib/node_modules/redis-commander/node_modules/browserify/index.js:204
        self[key] = w[key].bind(w);
                           ^
TypeError: Cannot call method 'bind' of undefined
    at /home/saya/.nvm/v0.11.7/lib/node_modules/redis-commander/node_modules/browserify/index.js:204:28
    at Array.forEach (native)
    at module.exports (/home/saya/.nvm/v0.11.7/lib/node_modules/redis-commander/node_modules/browserify/index.js:203:41)
    at module.exports (/home/saya/.nvm/v0.11.7/lib/node_modules/redis-commander/lib/app.js:48:11)
    at startWebApp (/home/saya/.nvm/v0.11.7/lib/node_modules/redis-commander/bin/redis-commander.js:158:3)
    at /home/saya/.nvm/v0.11.7/lib/node_modules/redis-commander/bin/redis-commander.js:116:10
    at /home/saya/.nvm/v0.11.7/lib/node_modules/redis-commander/lib/util.js:135:7
    at fs.js:255:14
    at Object.oncomplete (fs.js:96:15)
```

**Comment by sseide** [comment]
Older nodejs versions are EOL by now and not supported anymore. Please use recent version that is supported by NodeJs.org to get Redis Commander running.
