### ISSUE TITLE
error connecting

### ISSUE THREAD

**Issue by EddyF** [joeferner/redis-commander#150]
I used to have an instance on port 6380 now I currently only use 6379  but redis-commander still tries to listen to 6380 and returns error when I try to start the service.
I removed, cleaned npm cache and installed it again, also tried passing params to look for single port
still returns same issue.
any clues?

Redis error Error: Redis connection to localhost:6380 failed - connect ECONNREFUSED
  at RedisClient.on_error (/usr/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
  at Socket.<anonymous> (/usr/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
  at Socket.emit (events.js:95:17)
  at net.js:440:14
  at process._tickCallback (node.js:419:13)

Connection closed. Attempting to Reconnect...
Redis error Error: Redis connection to localhost:1010 failed - connect ECONNREFUSED
  at RedisClient.on_error (/usr/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
  at Socket.<anonymous> (/usr/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
  at Socket.emit (events.js:95:17)
  at net.js:440:14
  at process._tickCallback (node.js:419:13)

Connection closed. Attempting to Reconnect...
Redis error Error: Redis connection to localhost:6381 failed - connect ECONNREFUSED
  at RedisClient.on_error (/usr/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
  at Socket.<anonymous> (/usr/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
  at Socket.emit (events.js:95:17)
  at net.js:440:14
  at process._tickCallback (node.js:419:13)

Connection closed. Attempting to Reconnect...
Redis Connection localhost:6379 Using Redis DB #0
Connection closed. Attempting to Reconnect...
Redis connection gone from end event.

**Comment by EddyF** [comment]
I fixed this issue by removing the "~/.redis-commander" file. 
For some reason unnistall does not remove it, and cache cleaner doesnt either.
# rm ~/.redis-commander

**Comment by mitchellporter** [comment]
@EddyF Thanks worked perfectly!
