### ISSUE TITLE
Error on first install

### ISSUE THREAD

**Issue by emersonthis** [joeferner/redis-commander#157]
Maybe the docs just need to be updated, but this is what happens if I follow the instructions on npm...

```
$ npm insall -g redis-commander
$ redis-commander
No config found or was invalid.
Using default configuration.
No Save: false
listening on  0.0.0.0 : 8081
Redis error Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Connection closed. Attempting to Reconnect...
Redis error Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Redis error Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Redis error Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Redis error Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Redis error Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Redis error Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Redis error Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
Redis error Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:149:24)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:83:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
```

Maybe I just need to add the config settings first?

**Comment by sseide** [comment]
As the error message shows it tries to connect to local redis instance if nothing else is given.

If you need to connect to a different redis server you must provide all neccessary informations via command line or config file as stated in the README.
