### ISSUE TITLE
fails to auth after closing initial process

### ISSUE THREAD

**Issue by peakay** [joeferner/redis-commander#162]
Redis error Error: Auth error: ERR invalid password
    at Command.callback (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:172:43)
    at RedisClient.return_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:502:25)
    at RedisReplyParser.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:262:14)
    at RedisReplyParser.EventEmitter.emit (events.js:95:17)
    at RedisReplyParser.send_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/lib/parser/javascript.js:266:14)
    at RedisReplyParser.execute (/usr/local/lib/node_modules/redis-commander/node_modules/redis/lib/parser/javascript.js:125:22)
    at RedisClient.on_data (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:478:27)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:79:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)

For whatever reason redis commander only auths successfully on first run and yes I've triple checked the requirepass and what not.

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
