### ISSUE TITLE
Windows, Not Working

### ISSUE THREAD

**Issue by tigerclawn82** [joeferner/redis-commander#168]
Hi,
   Getting following error when trying to connect

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at Deps.lookupPackage (C:\Users\Administrator\AppData\Roaming\npm\node_modules\redis-commander\node_modules\module-deps\index.js:452:29)
    at Deps._transform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\redis-commander\node_modules\module-deps\index.js:93:10)
    at Deps.Transform._read (C:\Users\Administrator\AppData\Roaming\npm\node_modules\redis-commander\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Deps.Transform._write (C:\Users\Administrator\AppData\Roaming\npm\node_modules\redis-commander\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at Labeled.Pipeline._write (C:\Users\Administrator\AppData\Roaming\npm\node_modules\redis-commander\node_modules\stream-splicer\index.js:73:22)
    at doWrite (C:\Users\Administrator\AppData\Roaming\npm\node_modules\redis-commander\node_modules\readable-stream\lib\_stream_writable.js:279:12)
    at writeOrBuffer (C:\Users\Administrator\AppData\Roaming\npm\node_modules\redis-commander\node_modules\readable-stream\lib\_stream_writable.js:266:5)
    at Labeled.Writable.write (C:\Users\Administrator\AppData\Roaming\npm\node_modules\redis-commander\node_modules\readable-stream\lib\_stream_writable.js:211:11)

```

**Comment by Uxio0** [comment]
Same on Linux:
`path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Deps.lookupPackage (/usr/lib/node_modules/redis-commander/node_modules/module-deps/index.js:452:29)
    at Deps._transform (/usr/lib/node_modules/redis-commander/node_modules/module-deps/index.js:93:10)
    at Deps.Transform._read (/usr/lib/node_modules/redis-commander/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Deps.Transform._write (/usr/lib/node_modules/redis-commander/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at Labeled.Pipeline._write (/usr/lib/node_modules/redis-commander/node_modules/stream-splicer/index.js:73:22)
    at doWrite (/usr/lib/node_modules/redis-commander/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/usr/lib/node_modules/redis-commander/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Labeled.Writable.write (/usr/lib/node_modules/redis-commander/node_modules/readable-stream/lib/_stream_writable.js:211:11)`

**Comment by lludol** [comment]
Try with the node.js LTS version and it will work (v4.4.4).

So, this module is not compatible with node.js v6...

**Comment by marclennox** [comment]
Great, would you mind creating a pull request against my project?  :)

**Comment by HarelM** [comment]
Still not working on latest stable Node (v6.11) on windows. 
Something with permissions and the fact that it does not create a folder called `.redir-commander` but a file.

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.

**Comment by KooshkakiH** [comment]
Hi 
I have problem on runnig...


C:\Users\admin>redis-commander
C:\Users\admin\AppData\Roaming\npm\node_modules\redis-commander\node_modules\config\lib\config.js:793
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: '\Users\admin\AppData\Roaming\npm\node_modules\redis-commander\config\local-development.json': SyntaxError: Unexpected end of JSON input
    at Config.util.parseFile (C:\Users\admin\AppData\Roaming\npm\node_modules\redis-commander\node_modules\config\lib\config.js:793:11)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\redis-commander\node_modules\config\lib\config.js:601:26
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (C:\Users\admin\AppData\Roaming\npm\node_modules\redis-commander\node_modules\config\lib\config.js:600:16)
    at new Config (C:\Users\admin\AppData\Roaming\npm\node_modules\redis-commander\node_modules\config\lib\config.js:116:27)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\redis-commander\node_modules\config\lib\config.js:1430:31)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900
