### ISSUE TITLE
application failure while trying to add second server

### ISSUE THREAD

**Issue by Infernoman** [joeferner/redis-commander#180]
Trying to add a second server into redis-commander using the web interface. currently crashing because its trying to set http headers after theyve already been sent.

/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:43
    fn = function () { throw arg; };
                                 ^
    Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:724:11)

```
at ServerResponse.res.setHeader (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/express/node_modules/connect/lib/patch.js:134:22)

at ServerResponse.res.set.res.header (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/express/lib/response.js:595:10)

at ServerResponse.res.send (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/express/lib/response.js:151:12)

at /home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/lib/routes/apiv1.js:678:13

at /home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/async/lib/async.js:153:29

at sizeCallback (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/lib/routes/apiv1.js:654:17)

at tryCatcher (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)

at Promise.successAdapter (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/nodeify.js:23:30)

at Promise._settlePromiseAt (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:579:21)

at Promise._settlePromises (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:697:14)

at Async._drainQueue (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)

at Async._drainQueues (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)

at Async.drainQueues (/home/alastair/.nvm/v0.10.46/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)

at process._tickCallback (node.js:458:13)
```

`

**Comment by fkpp** [comment]
Same happens here.
redis-commander installed via npm, nodejs via yum epel.

OS is centos 6.7


```found 25312 keys for ""
found 30732 keys for ""

/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                                 ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:724:11)
    at ServerResponse.res.setHeader (/usr/lib/node_modules/redis-commander/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/usr/lib/node_modules/redis-commander/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.send (/usr/lib/node_modules/redis-commander/node_modules/express/lib/response.js:151:12)
    at /usr/lib/node_modules/redis-commander/lib/routes/apiv1.js:678:13
    at Object.async.forEachLimit (/usr/lib/node_modules/redis-commander/node_modules/async/lib/async.js:130:20)
    at /usr/lib/node_modules/redis-commander/lib/routes/apiv1.js:642:13
    at tryCatcher (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:579:21)
    at Promise._settlePromises (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)
```

`# npm list -g redis-commander
npm WARN unmet dependency /usr/lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
/usr/lib
└── redis-commander@0.4.2
`


`# yum info nodejs
Installed Packages
Name        : nodejs
Arch        : x86_64
Version     : 0.10.42
Release     : 4.el6
Size        : 7.0 M
Repo        : installed
From repo   : epel
`

**Comment by muhammadalie** [comment]
any Solutions?

**Comment by fkpp** [comment]
I got it working again using a pre 0.4.x version:

npm -g install redis-commander@0.3.2

**Comment by Dindaleon** [comment]
yes, 0.4.x versions are not working correctly :(

**Comment by truthadjustr** [comment]
same here too.. so I'm for now using version 0.3.2

**Comment by asmodehn** [comment]
same here.

Trying to add another server (same host, same port, different DB):

```
/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.res.setHeader (/usr/lib/node_modules/redis-commander/node_modules/express/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/usr/lib/node_modules/redis-commander/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.send (/usr/lib/node_modules/redis-commander/node_modules/express/lib/response.js:151:12)
    at /usr/lib/node_modules/redis-commander/lib/routes/apiv1.js:678:13
    at /usr/lib/node_modules/redis-commander/node_modules/async/lib/async.js:153:29
    at sizeCallback (/usr/lib/node_modules/redis-commander/lib/routes/apiv1.js:654:17)
    at tryCatcher (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/redis-commander/node_modules/ioredis/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by ea167** [comment]
Same here 

/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.res.setHeader (/usr/local/lib/node_modules/redis-commander/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/usr/local/lib/node_modules/redis-commander/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.send (/usr/local/lib/node_modules/redis-commander/node_modules/express/lib/response.js:151:12)
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:678:13
    at /usr/local/lib/node_modules/redis-commander/node_modules/async/lib/async.js:153:29
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:668:11
    at replenish (/usr/local/lib/node_modules/redis-commander/node_modules/async/lib/async.js:144:17)
    at /usr/local/lib/node_modules/redis-commander/node_modules/async/lib/async.js:156:29
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:668:11
    at replenish (/usr/local/lib/node_modules/redis-commander/node_modules/async/lib/async.js:144:17)
    at Object.async.forEachLimit (/usr/local/lib/node_modules/redis-commander/node_modules/async/lib/async.js:161:11)
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:642:13
    at tryCatcher (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/promise.js:582:21)

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
