### ISSUE TITLE
RPUSH command wont work when using import function

### ISSUE THREAD

**Issue by Dindaleon** [joeferner/redis-commander#184]
Hello,

When importing data into a database, all commands work except RPUSH. I am using version 0.3.2 because 0.4.x wont work.

this is the error:

```
/usr/local/lib/node_modules/redis-commander/node_modules/node-redis-dump/lib/node-redis-dump.js:402
                        callArgs = args.match(new RegExp('"?(.+?)"?\\s+"?([0-9]+?)"?(?:\\s|$)', 'i')).slice(1, 3);
                                                                                                     ^

TypeError: Cannot read property 'slice' of null
    at null.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/node-redis-dump/lib/node-redis-dump.js:402:84)
    at null.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/node-redis-dump/lib/node-redis-dump.js:423:4)
    at fn (/usr/local/lib/node_modules/redis-commander/node_modules/node-redis-dump/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/redis-commander/node_modules/node-redis-dump/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by sseide** [comment]
The feature requested is available with latest version.

If there is something missing at the implementation feel free to reopen issue with an updated description.
