### ISSUE TITLE
TypeError: Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by borisovg** [joeferner/redis-commander#185]
Crash when right-clicking on host in left nav, selecting disconnect and confirming in pop-up window.

```
/home/borisov/test/redis/node_modules/redis-commander/lib/routes/home.js:142
    if (notRemoved && connection.options.host == hostname && connection.options.port == port && connection.options.db == db) {
                                        ^

TypeError: Cannot read property 'host' of undefined
    at /home/borisov/test/redis/node_modules/redis-commander/lib/routes/home.js:142:41
    at Array.forEach (native)
    at removeConnectionFromDefaults (/home/borisov/test/redis/node_modules/redis-commander/lib/routes/home.js:127:15)
    at /home/borisov/test/redis/node_modules/redis-commander/lib/routes/home.js:101:7
    at /home/borisov/test/redis/node_modules/redis-commander/lib/util.js:144:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

redis-commander version 0.4.2

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
