### ISSUE TITLE
Adding a new connection causes a crash

### ISSUE THREAD

**Issue by Jiia** [joeferner/redis-commander#196]
I'd like to have two redis connections, one to db1 and other to db0.

When you add another connection redis-commander will crash. It happens if you add a new connection in the web interface or if you add multiple connections to your .redis-commander config file. The crash occurs when the web interface is opened. Tested on node 5.9.0 and 7.8.0.

```
$ redis-commander
No Save: true
listening on  0.0.0.0 : 8081
Redis Connection 127.0.0.1:6379 Using Redis DB #0
Redis Connection 127.0.0.1:6379 Using Redis DB #0
loading keys by prefix ""
found 155 keys for ""
found 1 keys for ""
/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.res.setHeader (/usr/local/lib/node_modules/redis-commander/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/usr/local/lib/node_modules/redis-commander/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.contentType.res.type (/usr/local/lib/node_modules/redis-commander/node_modules/express/lib/response.js:462:15)
    at ServerResponse.res.send (/usr/local/lib/node_modules/redis-commander/node_modules/express/lib/response.js:128:14)
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:678:13
    at /usr/local/lib/node_modules/redis-commander/node_modules/async/lib/async.js:153:29
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:668:11
    at replenish (/usr/local/lib/node_modules/redis-commander/node_modules/async/lib/async.js:144:17)
    at Object.async.forEachLimit (/usr/local/lib/node_modules/redis-commander/node_modules/async/lib/async.js:161:11)
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:642:13
    at tryCatcher (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/async.js:123:16)
```

Config file for reference

```
{
    "sidebarWidth": "250",
    "locked": "false",
    "CLIHeight": "420",
    "CLIOpen": "true",
    "default_connections": [
      {
        "label": "DEV",
        "host": "127.0.0.1",
        "port": "6379",
        "password": "",
        "dbIndex": "0"
      },
      {
        "label": "TEST",
        "host": "127.0.0.1",
        "port": "6379",
        "password": "",
        "dbIndex": "1"
      }
    ]
}
```

**Comment by SeanC2222** [comment]
See your other issue, #195, I commented there.

**Comment by SeanC2222** [comment]
@Jiia I think I fixed the issue. Get the updated version and close this issue if you are no longer experiencing any problems.

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
