### ISSUE TITLE
Failure on startup (Windows)

### ISSUE THREAD

**Issue by mrichman** [joeferner/redis-commander#212]
I just installed NPM 5.3.0 on Windows, and installed redis-commander via `npm install -g redis-commander`:

```
C:\windows\system32>npm install -g redis-commander
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
C:\Users\mrichman\AppData\Roaming\npm\redis-commander -> C:\Users\mrichman\AppData\Roaming\npm\node_modules\redis-commander\bin\redis-commander.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\redis-commander\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ redis-commander@0.4.3
added 470 packages in 160.435s
```

 and when I run `redis-commander` (as administrator) I get this error:

```
C:\windows\system32>redis-commander
{ Error: ENOENT: no such file or directory, open 'C:\Users\mrichman\.redis-commander'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\mrichman\\.redis-commander' }
No config found or was invalid.
Using default configuration.
No Save: true
listening on  0.0.0.0 : 8081
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8081
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1322:14)
    at listenInCluster (net.js:1370:12)
    at doListen (net.js:1492:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

C:\windows\system32>
```

**Comment by mrichman** [comment]
Apparently McAfee was using port 8081. Switching ports using `-p <port>` fixed it.
