### ISSUE TITLE
Redis run Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by servc4** [joeferner/redis-commander#223]
Hi
I get this Error when i try to runn redis Commander

```
root@vps:~# redis-commander
No Save: true

/usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:166
       myutil.encodeHTMLEntities(JSON.stringify(Object.assign({ ttl }, details
                                                                    ^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/local/lib/node_modules/redis-commander/lib/routes/index.js:5:3)
    at module.exports (/usr/local/lib/node_modules/redis-commander/lib/app.js:62:22)
    at startWebApp (/usr/local/lib/node_modules/redis-commander/bin/redis-commander.js:241:3)
    at /usr/local/lib/node_modules/redis-commander/bin/redis-commander.js:190:10
    at /usr/local/lib/node_modules/redis-commander/lib/util.js:144:5
    at fs.js:268:14
    at /usr/local/lib/node_modules/redis-commander/node_modules/browserify-middleware/node_modules/watchify/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at Object.oncomplete (fs.js:107:15)
```

My config .redis-commander

`{"sidebarWidth":"250","locked":"false","CLIHeight":"420","CLIOpen":"true","default_connections":[{"label":"local","host":"127.0.0.1","port":"6379","password":"","dbIndex":"0"}]}`

**Comment by whytobe** [comment]
Me too, on Amazon Linux 

`
{ [Error: EISDIR, read] errno: 28, code: 'EISDIR' }
No config found or was invalid.
Using default configuration.
No Save: true

/usr/lib/node_modules/redis-commander/lib/routes/apiv1.js:166
       myutil.encodeHTMLEntities(JSON.stringify(Object.assign({ ttl }, details
                                                                    ^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/lib/node_modules/redis-commander/lib/routes/index.js:5:3)
    at module.exports (/usr/lib/node_modules/redis-commander/lib/app.js:62:22)
    at startWebApp (/usr/lib/node_modules/redis-commander/bin/redis-commander.js:241:3)
    at /usr/lib/node_modules/redis-commander/bin/redis-commander.js:190:10
    at /usr/lib/node_modules/redis-commander/lib/util.js:134:7
    at fs.js:243:16
    at /usr/lib/node_modules/redis-commander/node_modules/browserify-middleware/node_modules/watchify/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at Object.oncomplete (fs.js:108:15)
`

but move back to version 0.4.4 works fine.

**Comment by antoniodipinto** [comment]
I've solved retrieving the old piece of code replacing in lib/routes/apiv1.js at line 166:
 
This
```
myutil.encodeHTMLEntities(JSON.stringify(Object.assign({ ttl }, details)), function (string) {
         res.send(string);
});
```

With this, found at this commit https://github.com/joeferner/redis-commander/commit/76a6b147891a910860ad4d9afc7723ee94e7e5fd
```
myutil.encodeHTMLEntities(JSON.stringify(details), function (string) {
                res.send(string);
});
```

Take care, this will modify redis ttl connection, this is just my try to fix this and it seems to work.

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
