### ISSUE TITLE
Cannot Disconnect From Remote Redis Server

### ISSUE THREAD

**Issue by SpaceVarmint** [joeferner/redis-commander#237]
When I try to disconnect from any Redis instance, there is no change in the user interface and the program crashes. 

Using Linux Mint 18.3
Installed redis-commander with npm -g install redis-commander (today)
Node ver.: 4.2.6~dfsg-1ubuntu4.1

Everything else seems to work.

I got the following  as the last output before the crash. Not sure if completely relevant, but very likely.

 /usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.res.setHeader (/usr/local/lib/node_modules/redis-commander/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.set.res.header (/usr/local/lib/node_modules/redis-commander/node_modules/express/lib/response.js:595:10)
    at ServerResponse.res.send (/usr/local/lib/node_modules/redis-commander/node_modules/express/lib/response.js:151:12)
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:724:13
    at /usr/local/lib/node_modules/redis-commander/node_modules/async/lib/async.js:153:29
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:710:15
    at tryCatcher (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/redis-commander/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by sseide** [comment]
npm version is really old by now. Please check with latest version from github or use docker image. They got a lot of fixes since then...

An please update NodeJS to version 6.x or newer. NodeJS 4.x is EOL since half a year.
