### ISSUE TITLE
Select DB: redisConnection is not defined

### ISSUE THREAD

**Issue by Dwlad90** [joeferner/redis-commander#274]
`ReferenceError: redisConnection is not defined
at /redis-commander/lib/routes/apiv1.js:108:17
at getConnection (/redis-commander/lib/routes/apiv1.js:46:10)
at postExec (/redis-commander/lib/routes/apiv1.js:107:3)
at Layer.handle [as handle_request] (/redis-commander/node_modules/express/lib/router/layer.js:95:5)
at next (/redis-commander/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/redis-commander/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/redis-commander/node_modules/express/lib/router/layer.js:95:5)
at /redis-commander/node_modules/express/lib/router/index.js:281:22
at Function.process_params (/redis-commander/node_modules/express/lib/router/index.js:335:12)
at next (/redis-commander/node_modules/express/lib/router/index.js:275:10)
at jwtVerify.then.success (/redis-commander/lib/app.js:215:14)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by W1M0R** [comment]
I have the same issue.

**Comment by dfdumaresq** [comment]
I have the same issue; sending commands in redis-commander causes a 500 error on the client (Chrome) and on the server-side: ReferenceError: redisConnection is not defined

**Comment by dfdumaresq** [comment]
Luckily I can telnet to my Redis host and issue commands from the command line.

$ telnet redis 6379
Trying 10.10.10.100...
Connected to redis.
Escape character is '^]'.

INFO
$2701
# Server
redis_version:4.0.10
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:3e68f04515f466a2
redis_mode:standalone
os:Linux 4.9.87-linuxkit-aufs x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.3.0
