### ISSUE TITLE
Broken on first install

### ISSUE THREAD

**Issue by zwhitchcox** [joeferner/redis-commander#329]
`npm i -g redis-commander`
`redis-commander`
```
{ Error: ENOENT: no such file or directory, open '/home/zane/.redis-commander'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/zane/.redis-commander' }
No config found or was invalid.
Using default configuration.
No Save: false
listening on  0.0.0.0 : 8081
Redis Connection localhost:6379 Using Redis DB #0
No config found.
Using default configuration.
/home/zane/.nvm/versions/node/v9.11.1/lib/node_modules/redis-commander/lib/routes/home.js:40
      reducedConfig.default_connections.forEach(function(item) {
                                        ^

TypeError: Cannot read property 'forEach' of undefined
    at /home/zane/.nvm/versions/node/v9.11.1/lib/node_modules/redis-commander/lib/routes/home.js:40:41
    at ReadFileContext.callback (/home/zane/.nvm/versions/node/v9.11.1/lib/node_modules/redis-commander/lib/util.js:130:7)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)

```

**Comment by michaelotis** [comment]
Same issue

**Comment by sseide** [comment]
Yes - npm version is not up to date and missing some of the latest bug fixes in git repo and Docker image. Docker image is rebuild automatically and on par with latest github version.

**Comment by sseide** [comment]
btw - there was a new redis-commander release at npm which contains the fix for this bug.
Can this issue be closed?
