### ISSUE TITLE
docker container startup with no args yields unexpected error about ports

### ISSUE THREAD

**Issue by ancmikesmullin** [joeferner/redis-commander#377]
basically the default value for the `--redis-port` param is some string where a number is evidently expected. should probably replace `tcp://172.17.0.2:6379` with a safe default like `6379`.

```
17:21:21.965 redis-commander | Creating custom redis-commander config '/redis-commander/config/local-production.json'.                            
17:21:21.967 redis-commander | node ./bin/redis-commander --redis-port tcp://172.17.0.2:6379 --redis-host redis                                   
17:21:22.078 redis-commander | Using scan instead of keys                                                                                         
17:21:22.081 redis-commander | No Save: false                                                                                                     
17:21:22.383 redis-commander | listening on 0.0.0.0:8081                                                                                          
17:21:22.383 redis-commander | access with browser at http://127.0.0.1:8081                                                                       
17:21:22.384 redis-commander | setUpConnection (R:redis:NaN:0) Redis error RangeError: "port" option should be >= 0 and < 65536: NaN              
17:21:22.384 redis-commander |     at lookupAndConnect (net.js:1052:13)                                                                           
17:21:22.384 redis-commander |     at Socket.connect (net.js:1025:5)                                                                              
17:21:22.384 redis-commander |     at Object.connect (net.js:117:35)                                                                              
17:21:22.384 redis-commander |     at process.nextTick (/redis-commander/node_modules/ioredis/built/connectors/StandaloneConnector.js:58:45)      
17:21:22.384 redis-commander |     at _combinedTickCallback (internal/process/next_tick.js:132:7)                                                 
17:21:22.384 redis-commander |     at process._tickCallback (internal/process/next_tick.js:181:9)                                                 
17:21:22.384 redis-commander |     at Function.Module.runMain (module.js:696:11)                                                                  
17:21:22.384 redis-commander |     at startup (bootstrap_node.js:204:16)                                                                          
17:21:22.384 redis-commander |     at bootstrap_node.js:625:3                                                                                     
17:21:22.384 redis-commander | setUpConnection (R:redis:NaN:0) Redis error RangeError: "port" option should be >= 0 and < 65536: NaN              
17:21:22.384 redis-commander |     at lookupAndConnect (net.js:1052:13)                                                                           
17:21:22.384 redis-commander |     at Socket.connect (net.js:1025:5)                                                                              
17:21:22.384 redis-commander |     at Object.connect (net.js:117:35)                                                                              
17:21:22.384 redis-commander |     at process.nextTick (/redis-commander/node_modules/ioredis/built/connectors/StandaloneConnector.js:58:45)      
17:21:22.384 redis-commander |     at _combinedTickCallback (internal/process/next_tick.js:132:7)                                                 
17:21:22.384 redis-commander |     at process._tickCallback (internal/process/next_tick.js:181:9)                                                 
17:21:22.384 redis-commander |     at Function.Module.runMain (module.js:696:11)                                                                  
17:21:22.384 redis-commander |     at startup (bootstrap_node.js:204:16)                                                                          
17:21:22.384 redis-commander |     at bootstrap_node.js:625:3                                                                                     
17:21:22.385 redis-commander | connection (R:redis:NaN:0) closed. Attempting to Reconnect...                                                      
17:21:22.385 redis-commander | connection (R:redis:NaN:0) closed. Attempting to Reconnect...   
```

**Comment by ancmikesmullin** [comment]
my docker command was
`docker run --rm --name redis-commander -p 127.0.0.1:8081:8081 --link redis rediscommander/redis-commander`

**Comment by sseide** [comment]
two distinct problems here:

1. starting redis commander without giving it any configuration where to connect to does not make sense in container context - redis commander needs a configuration (env vars or json config files) where to find the redis server. You need to explicitly set REDIS_HOST or similiar to configure redis commander.
If no configuration is given it tries to connect to localhost  - fallback for all users running it locally to manage their local redis servers via stand-aone app

2. starting docker container with `--link` basically just says "this container is allowed to communicate via network with the other (linked) container". Nothing more.It does not automagically  wire up some connections between them. Yu can linkt to two/three/four redis servers if you like but need to provide the connection data for redis commander none-the-less.

Where the REDIS_PORT env var does come from i cannot say. Some other process set this somehow...

3. You are right - getting invalid values it should not just complain about it (line 7) but not try to start this connection at all and error out instead... this should be fixed on our side

**Comment by ancmikesmullin** [comment]
I eventually figured out 1 and 2 so this is mainly just FYI for 3. Thanks.

**Comment by sseide** [comment]
ok, added some validation for port and db index for better error messages and added parsing of this kind of `REDIS_PORT` information too. Seen this `tcp://1.2.3.4:6379` kind of port information on different occasions already. Redis Commander parses this now and your original setup should work out of the box without setting any args at all...

The `REDIS_PORT` env var comes from linking the containers with the 'redis' one. See here https://github.com/docker-library/redis/issues/53 - answer from "tianon"

New version available on github and dockerhub.

**Comment by sseide** [comment]
@ancmikesmullin does work now for you? Can ticket be closedor are there other problems related to this?

**Comment by sseide** [comment]
new version 0.6.7 with fix available on npm too
