### ISSUE TITLE
Application Crashes When MONITOR command is entered via console

### ISSUE THREAD

**Issue by VamsiKrishna-av96** [joeferner/redis-commander#424]
scanning: 1: 1
setUpConnection (R:undefined:undefined:undefined) Redis error Error: Command queue state error. If you can reproduce this, please report it. Last reply: 0,
    at DataHandler.shiftCommand (/usr/local/lib/node_modules/redis-commander/node_modules/ioredis/built/DataHandler.js:164:27)
    at DataHandler.returnReply (/usr/local/lib/node_modules/redis-commander/node_modules/ioredis/built/DataHandler.js:50:27)
    at JavascriptRedisParser.returnReply (/usr/local/lib/node_modules/redis-commander/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/usr/local/lib/node_modules/redis-commander/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (node:events:327:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at Socket.Readable.push (node:internal/streams/readable:218:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:192:23)

/usr/local/lib/node_modules/redis-commander/node_modules/standard-as-callback/built/index.js:6
        throw e;
        ^

TypeError: serverInfo.split is not a function
    at /usr/local/lib/node_modules/redis-commander/lib/routes/apiv1.js:212:8
    at tryCatcher (/usr/local/lib/node_modules/redis-commander/node_modules/standard-as-callback/built/utils.js:11:23)
    at /usr/local/lib/node_modules/redis-commander/node_modules/standard-as-callback/built/index.js:19:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
![screenshot](https://user-images.githubusercontent.com/61381489/100462217-f1624b80-30ef-11eb-854b-986bb35f55f4.png)

**Comment by sseide** [comment]
same reason why #385 is there. MONITOR command blocks current redis connection, therefore no other commands possible to redraw the tree view and so on (only one connection used for everything). By now MONITOR command will be blocked in cli and can be reenabled after #385 is solved.
