### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by haikalrios** [joeferner/redis-commander#450]
Hello everyone, 

someone have a ideal about this error when try import by redis-commander:

version:

```
$ npm list -g redis-commander
-- redis-commander@0.7.0
```

Sample data tried to Import

`SET "traefik/http/services/xtpo-services/loadBalancer/healthCheck/path" "/heathcheck"`

```
${path}\npm\node_modules\redis-commander\node_modules\node-redis-dump\lib\node-redis-dump.js:420
                                this.getClient()[ command ].apply(this.getClient(), callArgs);
                                                           ^

TypeError: Cannot read property 'apply' of undefined
    at module.exports.<anonymous> (${path}\npm\node_modules\redis-commander\node_modules\node-redis-dump\lib\node-redis-dump.js:420:32)
    at module.exports.<anonymous> (${path}\npm\node_modules\redis-commander\node_modules\node-redis-dump\lib\node-redis-dump.js:423:4)
    at fn (${path}\npm\node_modules\redis-commander\node_modules\node-redis-dump\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (${path}\npm\node_modules\redis-commander\node_modules\node-redis-dump\node_modules\async\lib\async.js:498:34)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by sseide** [comment]
Hello,

cannot reproduce with latest version. Can you please install Redis Commander from git and test again?
Current master works fine. Same as Docker image

Sorry but there were no npm release for some time as its a bit difficult right now.

Best regards,
S. Seide

**Comment by sseide** [comment]
close as probably fixed, please reopen with instructions on how to reproduce if it is not
