### ISSUE TITLE
Redis error Error: Ready check failed: ERR operation not permitted

### ISSUE THREAD

**Issue by yt8jbe7q63** [joeferner/redis-commander#91]
I'm running redis-2.6.13 on CentOS 6. 

I am seeing the following error when redis-commander is started.
How can I fix it? Thanks.

[root@centos63 redis-commander-master]# redis-commander --redis-password=<password> -p 8888
path.existsSync is now called `fs.existsSync`.
listening on  8888
Redis error Error: Ready check failed: ERR operation not permitted
    at RedisClient.on_info_cmd (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:319:35)
    at Command.callback (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:367:14)
    at RedisClient.return_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:502:25)
    at RedisReplyParser.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:262:14)
    at RedisReplyParser.EventEmitter.emit (events.js:97:17)
    at RedisReplyParser.send_error (/usr/local/lib/node_modules/redis-commander/node_modules/redis/lib/parser/javascript.js:266:14)
    at RedisReplyParser.execute (/usr/local/lib/node_modules/redis-commander/node_modules/redis/lib/parser/javascript.js:125:22)
    at RedisClient.on_data (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:478:27)
    at Socket.<anonymous> (/usr/local/lib/node_modules/redis-commander/node_modules/redis/index.js:79:14)
    at Socket.EventEmitter.emit (events.js:97:17)
    at Socket.<anonymous> (_stream_readable.js:720:14)
    at Socket.EventEmitter.emit (events.js:94:17)
    at emitReadable_ (_stream_readable.js:392:10)
    at emitReadable (_stream_readable.js:388:5)
    at readableAddChunk (_stream_readable.js:150:9)
    at Socket.Readable.push (_stream_readable.js:113:10)
    at TCP.onread (net.js:515:21)
Redis Connection localhost:6379 Using Redis DB #0

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
