### ISSUE TITLE
Attempting to install redis-commander with latest NPM fails

### ISSUE THREAD

**Issue by lukeasrodgers** [joeferner/redis-commander#99]
npm versions 1.3.0 and 1.3.1
OSX 10.8.4

Error:

```
...
npm ERR! TypeError: Invalid Version: 2.0.0beta
npm ERR!     at new SemVer (/Users/luke/local/lib/node_modules/npm/node_modules/semver/semver.js:257:11)
npm ERR!     at SemVer.compare (/Users/luke/local/lib/node_modules/npm/node_modules/semver/semver.js:296:13)
npm ERR!     at compare (/Users/luke/local/lib/node_modules/npm/node_modules/semver/semver.js:410:31)
npm ERR!     at rcompare (/Users/luke/local/lib/node_modules/npm/node_modules/semver/semver.js:420:10)
npm ERR!     at Array.sort (native)
npm ERR!     at Function.maxSatisfying (/Users/luke/local/lib/node_modules/npm/node_modules/semver/semver.js:838:6)
npm ERR!     at next (/Users/luke/local/lib/node_modules/npm/lib/cache.js:699:21)
npm ERR!     at /Users/luke/local/lib/node_modules/npm/lib/cache.js:678:5
npm ERR!     at saved (/Users/luke/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.4.0
npm ERR! command "node" "/Users/luke/local/bin/npm" "install" "-g" "redis-commander"
npm ERR! cwd /Users/luke
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.3.1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/luke/npm-debug.log
npm ERR! not ok code 0
```

My guess is that the version of express specified in package.json, https://github.com/nearinfinity/redis-commander/blob/master/package.json#L25, results in an attempt to parse all `2.x.x` versions of express, which then craps out on the first non-semver one, `2.0.0beta`.

**Comment by dewsaq** [comment]
Try sudo

**Comment by sseide** [comment]
This problem should be fixed in current version. 
If you think its not feel free to reopen issue with updated informations based on latest version.
